Improve installation script

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,9 +1,27 @@
-#!/usr/bin/env bash
+#!/bin/bash -i
 
+localbin="$HOME/.local/bin"
+globalbin="/usr/local/bin"
+bashrc="$HOME/.bashrc"
+tmp="/tmp/tgpt"
 
 ## Install script for GNU/Linux & MacOS
 
 set -e
+
+echo -e "Installation type?\n1) System wide installation
+2) User installation"
+read -r bindir
+if [ "$bindir" == "1" ]; then
+	bindir="$globalbin"
+	tgpt="${bindir}/tgpt"
+elif [ "$bindir" == "2"  ]; then
+	bindir="$localbin"
+	tgpt="${bindir}/tgpt"
+else
+	echo -e "Wrong installation type, exiting..."
+	exit 1
+fi
 
 # Check the system architecture
 if [[ $(uname -m) == "x86_64" ]]; then
@@ -30,19 +48,57 @@ echo -e "Processor Architecture: ${ARCH}\n"
 URL="https://github.com/aandrew-me/tgpt/releases/latest/download/tgpt-${OS}-${ARCH}"
 # Download the executable
 echo -e "Downloading...\n"
-curl -sSL "$URL" -o /tmp/tgpt
+curl -sSL "$URL" -o  "$tmp"
 
-# Move the executable to a directory in PATH (e.g. /usr/local/bin/ on Linux, /usr/local/bin/ or /usr/local/opt/ on macOS)
-if [[ $OS == "linux" ]]; then
-    sudo mv /tmp/tgpt /usr/local/bin/
-else
-    sudo mv /tmp/tgpt /usr/local/bin/
+if [ ! -d "$bindir" ]; then
+	if [ "$bindir" == "$globalbin" ]; then
+		sudo mkdir -p "$bindir"
+	else
+		mkdir -p "$bindir"
+	fi
 fi
 
-sudo chmod +x /usr/local/bin/tgpt
+# Move the executable to a directory in PATH (e.g. /usr/local/bin/ on Linux, /usr/local/bin/ or /usr/local/opt/ on macOS)
+if [[ "$OS" == "linux" ]]; then
+	if [ "$bindir" == "$globalbin" ]; then
+		sudo mv "$tmp" "$bindir"
+ 	else
+		mv "$tmp" "$bindir"
+	fi
+else
+        if [ "$bindir" == "$globalbin" ]; then
+                sudo mv "$tmp" "$bindir"
+        else
+                mv "$tmp" "$bindir"
+        fi
+fi
 
-echo -e "Installed Successfully \n"
+if [[ ":$PATH:" == *":$bindir:"* ]]; then
+	echo -e "Your path is correctly set"
+else
+	echo -e "Your path is missing ${bindir}"
+	if [[ "$SHELL" == "/bin/bash" && -f "$bashrc" ]]; then
+cat << EOF >> "$bashrc"
+export PATH="$bindir:$PATH"
+EOF
+	source "$bashrc"
+	echo -e "Added ${bindir} to path"
+	fi
+fi
 
-echo -e "Run tgpt -h to get started"
-
+if [ -f "$tgpt" ]; then
+	if [ "$bindir" == "$globalbin" ]; then
+		sudo chmod +x "$tgpt"
+	else
+		chmod +x "$tgpt"
+	fi
+	if [ $(which tgpt) ]; then
+		echo -e "Installed Successfully \n"
+		echo -e "Reload your terminal and run tgpt -h to get started"
+	else
+		echo -e "tgpt not found in ${bindir}"
+	fi
+else
+	echo -e "there is no tgpt in ${bindir}"
+fi
 
